### ISSUE TITLE
Not matching in preprocess data

### ISSUE THREAD

**Issue by anhoangphuc** [ando-khachatryan/HiDDeN#14]
Hi. I have a question about your code. 
In utils module, you normalize input into mean = 0.5 and std = 0.5. But in test_model module, you rerange input from [0, 1] to [-1, 1]. Can you explain why?

**Comment by ando-khachatryan** [comment]
They do the same thing.  Normalize does:
Z = (X - mean) / std,
so when X is in [0, 1], mean=std=0.5, then Z is in [-1, 1].

**Comment by anhoangphuc** [comment]
Thank you for your answer. :D.
