### ISSUE TITLE
Memory requirements for your experiments

### ISSUE THREAD

**Issue by yamizi** [ando-khachatryan/HiDDeN#15]
Dear Ando,
I would like to know how much memory / gpu is required to run the same experiments as yours.
Your 400 epochs trainining took about 20 hours according to train.csv
What is the configuration you used for your own? Is it close to the original paper?

On issue #12 ,  they were using  131663888 kB memory and still got out of memory error.
Is it that heavy?

Thank you very much

**Comment by ando-khachatryan** [comment]
The original #12 was the Lua+torch version by the original authors, not this repo. 
I ran my experiments using RTX 2070 (8GB) , and yes, it takes approx. 20 hours to run a 400-epoch experiment. However, you can reduce the batch size if you have less GPU memory. You can also switch the optimizer from Adam to SGD (which uses significantly less memory), but then you'd have to juggle a bit with SGD parameters.

On Nvidia RTX cards you can use 16-bit floats, see https://github.com/NVIDIA/apex
I did some initial experiments with this and there was about 25-30% speedup, and if I recall correctly memory usage went down as well. Back then this library had some issues with GAN losses, so I could not add it to the repo, but I know that they have fixed them. Note that if you are doing mass experiments on V100s in the cloud, definitely use apex as with V100s the speedup should be much larger.

**Comment by yamizi** [comment]
Thank you very much Ando for your reply and suggestions.
I will try with an RTX card :)

I will also ask the authors of the paper what configuration they did use. 
Best, Salah
