### ISSUE TITLE
Is embedding capacity ≈ 0.0006  when considering robustness？

### ISSUE THREAD

**Issue by LeeeLiu** [ando-khachatryan/HiDDeN#19]
Dear author，
When we consider watermarking（robustness），
the embedding capacity is  30   ÷   3   ÷   128   ÷   128  ≈ 0.00061， right？

**Comment by ando-khachatryan** [comment]
I'm not sure. We are embedding 30 bits into an image of size 3x128x128, so looking from that angle your number looks right. 
On the other hand, the image pixels are bytes, so you need at least 3x128x128x8 bits to store the image. Looking from that angle, we are storing 30 bits into 3x128x128x8 bits.

**Comment by LeeeLiu** [comment]
> I'm not sure. We are embedding 30 bits into an image of size 3x128x128, so looking from that angle your number looks right.
> On the other hand, the image pixels are bytes, so you need at least 3x128x128x8 bits to store the image. Looking from that angle, we are storing 30 bits into 3x128x128x8 bits.

OK，thanks！
