### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Ruandy** [ando-khachatryan/HiDDeN#8]
Hello, thanks for your code. I tried to run it but got a TypeError in HiDDeN/model/encoder.py line 40. The error log is: **expected Tensor as element 1 in argument 0, but got Sequential.** Is it caused by the different type of encoded_image and image?

**Comment by ando-khachatryan** [comment]
I'm not entirely sure, but probably something is wrong with the data you are passing to the model.
The data is passed on line 51 of train.py:
            `losses, _ = model.train_on_batch([image, message])`
If your batch size is, say, 12, the spatial size of the image is 128 x 128, then "image" you are passing to the model should be a torch.tensor of dimensions 12 x 3 x 128 x 128.

**Comment by Ruandy** [comment]
Is indeed the issue of the data, problem solved thanks.
